### ISSUE TITLE
Pruebas de cero-conocimiento

### ISSUE THREAD

**Issue by Avilocap** [mruwzum/decide-europa-mixnet#1]
Es necesario la implementación de las pruebas de algún tipo de prueba de cero-conocimiento que verifique la validez de la clave privada. Estas pruebas deben verificar dicha validez sin suministrar la propia clave privada.

**Comment by Naitrisc** [comment]
Se ha desarrollado un algoritmo para llevar a cabo la verificación de la validez de la clave privada sin suministrar dicha clave. Estas pruebas las hemos realizado siguiendo un paper de pruebas de cero conocimiento. 
En este commit se muestra nuestra posible solución: https://github.com/mruwzum/decide-europa-mixnet/commit/06418ac7e3a174e335b8ccaaf0db6d0565e36924
Esta solución está basada en el paper: [A Secure ElGamal Cryptosystem Using Zero Knowledge Protocol](https://goo.gl/W111FR)
