### ISSUE TITLE
Fallo al realizar el recuento de votos

### ISSUE THREAD

**Issue by Avilocap** [mruwzum/decide-europa-mixnet#2]
Creo una votación, empieza la votación, se cierra y a la hora de hacer el recuento aparece un fallo.
El fallo aparece tanto en local como en producción con docker.
El fallo aparece cuando hay votos para contar, así como cuando no se ha llevado a cabo la votación aún.
La traza del fallo es la siguiente: http://dpaste.com/3FV3V8E

**Comment by juanmv96** [comment]
Se procede a revisar el fallo y buscar una solución.
