### ISSUE TITLE
Guía de 'commit'

### ISSUE THREAD

**Issue by Naitrisc** [mruwzum/decide-europa-mixnet#3]
Se necesita formalizar en un documento, explicando en detalle cuando y como se van a realizar los _commits_ del equipo Europa-MIXNET.

@mruwzum

**Comment by Avilocap** [comment]
Se ha creado una [página en la wiki](https://github.com/mruwzum/decide-europa-mixnet/wiki/Gestión-del-código) donde se especifica detalladamente todo lo solicitado
