### ISSUE TITLE
Guía de la gestión de 'Issues'

### ISSUE THREAD

**Issue by Naitrisc** [mruwzum/decide-europa-mixnet#4]
Se necesita formalizar en un documento la guía de como llevar a cabo las _Issues_ tanto a nivel del equipo Europa-Mixnet como con el equipo de Europa.

**Comment by Avilocap** [comment]
Se ha creado una [página en la wiki](https://github.com/mruwzum/decide-europa-mixnet/wiki/Issues) donde se especifica detalladamente todo lo solicitado
