### ISSUE TITLE
Error en el fichero .travis.yml

### ISSUE THREAD

**Issue by mruwzum** [mruwzum/decide-europa-mixnet#6]
Al intentar ejecutar la pipeline de Travis, falla. Devuelve un error, build:failed: 

`0.02s$ python3 zkp.py
python3: can't open file 'zkp.py': [Errno 2] No such file or directory
The command "python3 zkp.py" exited with 2.`

# Pasos para la reproducción
- Iniciar sesión en https://travis-ci.com con nuestra cuenta de Github.
- Ejecutar el build de la pipeline mruwzum / decide-europa-mixnet

| Programa  | Versión |
| ------------- | ------------- |
| OS  |  10.13.6  |
| Python  | 3  |
| Safari  |  12.0.2  |

**Comment by Naitrisc** [comment]
Se procede a arreglar el fichero de .travis.yml

**Comment by mruwzum** [comment]
Arreglado con el commit: 60e10b8dba7361137313950d07ede570a79d4c4e
