### ISSUE TITLE
Error al trasladar las ZKP a las vistas

### ISSUE THREAD

**Issue by Naitrisc** [mruwzum/decide-europa-mixnet#7]
Al intentar acceder a la vista 'localhost:8000/mixnet/zkp/prueba2' se produce el error: __init__() missing 1 required positional argument: 'get_response'.

## Pasos para la reproducción:
*  Realizar la migración
*  Ejecutar el servidor
*  Ir a la ruta localhost:8080/mixnet/zkp/prueba2

## Detalles del sistema
| Programa  | Versión     | 
| ------------- |:-------------:| 
| OS | Ubuntu 18.04 | 
| Python    | 3.6.7      |
| Buscador | Firefox|

**Comment by Avilocap** [comment]
El error queda subsanado en el commit 847c1b77a9ef06ec4db3bc3e31d441be95472b52.

El error sucedia porque se estaban llamando a ciertas variables que no estaban creadas correctamente.
