### ISSUE TITLE
Error en el despliegue de travis [High]

### ISSUE THREAD

**Issue by Naitrisc** [mruwzum/decide-europa-mixnet#8]
Al ejecutar la útlima versión del código: https://github.com/mruwzum/decide-europa-mixnet se produce un error en travis-ci.

## Pasos para reproducir el error:
 + Establecer la conexión con travis-ci
 + Ejecutar build de travis
 + Se obtiene el error un error en cual especifica que el usuario no tiene permisos para crear la base de datos.

## Detalles del sistema
| Programa  | Versión     | 
| ------------- |:-------------:| 
| OS | Ubuntu 18.04 | 
| Python    | 3.6.7      |
| Buscador | Firefox|

**Comment by mruwzum** [comment]
Problema solucionado en el commit 4935e1c1d1f3d6d0e1a401cba421ccc7b3c77d41

**Comment by mruwzum** [comment]
El problema viene al in tentar ejecutar los test de Django en Travis. Existe un error conocido por el cual Travis no es capaz de destruir la base de datos creadas tras los tests, por lo que al realizarlos da un error.

Una investigación llevada a cabo sugire que existe un problema en la relación entre Heroku y travis por la cual la libreria django-heroku da problemas con Travis. Más información en este [enlace](https://stackoverflow.com/questions/50805897/django-unit-tests-failing-on-travis-ci-builds)

Se esta buscando una solución alternativa para poder llevar a cabo los test en Travis.

**Comment by mruwzum** [comment]
Se ha solucionado el error en el commit e4a3c5b2674f22442dff35f7099e80f1ac04d500
