### ISSUE TITLE
Bug con los formularios de ZKP

### ISSUE THREAD

**Issue by Naitrisc** [mruwzum/decide-europa-mixnet#9]
Al intentar realizar las pruebas de cero conocimiento con valores propios el sistema no es capaz de realizar las pruebas.

## Pasos para la reproducción:
*  Ejecutar servidor
*  Acceder a la ruta de las ZKP
*  Rellenar y subir el formulario

## Detalles del sistema
| Programa  | Versión     | 
| ------------- |:-------------:| 
| OS | Ubuntu 18.04 | 
| Python    | 3.6.7      |
| Buscador | Firefox|

**Comment by mruwzum** [comment]
Solucionado en el commit 044c3b8125ef3f22c3e5648ba717ca24b18b63ec
